#!/bin/bash

main() {
	local dir_base=/mnt/usb/upgrade
	#
	# prepare flag file
	#
	local file=${dir_base}/.usbupgrade_auto
	touch ${file}; fsync ${file}

	local rootfs=${dir_base}/rootfs
	__ROOTFS__=${rootfs} ${rootfs}/etc/upgrade/usbupgrade.sh
}

main
