#!/bin/bash

readonly dir_usbwebsite=/mnt/usb/upgrade/website
readonly file_usbwebsite_config=${dir_usbwebsite}/website.conf

#
#$1:info
#
usbwebsite_logger() {
	logger -t usbwebsite "$@"
}

#
#$1:info
#
usbwebsite_echo_logger() {
	echo usbwebsite "$@"
	logger -t usbwebsite "$@"
}

#
#$1:local version
#$2:config
#
usbwebsite_upgrade_version() {
	local version="$1"
	local config="$2"

	local target=$(awk -v version=${version} '{if ($1==version) print $2}' ${config})
	case $(echo ${target} | wc -l) in
	0)
		usbwebsite_logger "no found version, needn't upgrade"
		;;
	1)
		usbwebsite_logger "need upgrade: ${version}==>${target}"

		echo "${target}"
		;;
	*)
		usbwebsite_logger "too more version, don't upgrade"
		;;
	esac
}

#
#[upgrade version]
#
usbwebsite_upgrade() {
	local upgrade_version="$1"

	local action=$(basename $0)
	local on_rootfs="on rootfs:$(cat /etc/.version)"

	if [[ -z "${upgrade_version}" ]]; then
		local file=${__CP_WEBSITE__}/ver.info
		if [[ ! -f "${file}" ]]; then
			usbwebsite_echo_logger \
				"ERROR: not support ${action} ${on_rootfs}"

			return 1
		fi

		local local_version=$(cat ${file})
		upgrade_version=$(usbwebsite_upgrade_version \
							${local_version} \
							${file_usbwebsite_config})
		if [[ -z "${upgrade_version}" ]]; then
			usbwebsite_echo_logger \
				"${local_version} needn't upgrade ${on_rootfs}"

			return
		fi
	fi

	local src=${dir_usbwebsite}/${upgrade_version}
	local dst=${__CP_WEBSITE__}
	if  [[ ! -d "${src}" ]]; then
		usbwebsite_echo_logger \
			"no found ${upgrade_version}"

		return 1
	fi

	cp -fpR ${src}/* ${dst}; sync

	usbwebsite_echo_logger \
		"OK: upgrade ${local_version} to ${upgrade_version} ${on_rootfs}"
}

#
#[upgrade version]
#
main() {
	usbwebsite_upgrade "$@"
}

main "$@"
