#!/bin/bash

. ${__ROOTFS__}/etc/upgrade/dir.in

#
#$1:version
#$2:idx
#
rollback_md() {
	local version=$1
	local idx=$2

	remount_rootfs ${idx} rw
	echo ${version} > $(rootfs_dir ${idx})/etc/.version
#	remount_rootfs ${idx} rw
}

#
#$1:version
#
rollback_ap() {
	local version=$1

	${__ROOTFS__}/etc/jsock/jcmd.sh asyn "echo ${version} > /etc/.version"
}

#
#$1:version
#[$2:idx or ap]
#
main() {
	local version=$1
	local target=$2

	version_check ${version} || {
		echo "bad version:${version}"

		return
	}

	case "${target}" in
	"0" | "1" | "2")
		rollback_md ${version} ${target}
		;;
	"ap")
		rollback_ap ${version}
		;;
	"")
		rollback_md ${version} 0
		rollback_md ${version} 1
		rollback_md ${version} 2

		rollback_ap ${version}
		;;
	esac
}

main "$@"
