#!/bin/bash

. ${__ROOTFS__}/etc/utils/utils.in

main() {
#	local list="monitord monitors"
#	killall ${list} ${list} &> /dev/null

	list=$(list_cons \
		rsync_task.sh \
		handshake_ap.sh \
		upgrade_ap.sh \
		upgrade_factory.sh \
		websiteupgrade.sh \
		rsync \
		syslogd \
		sleep \
		crond \
		nginx \
		php-fpm \
		udhcpd \
		wifidog \
		telnetd \
		ntpclient \
		curl \
		platform.sh \
		stimer_system_startup.sh \
		stimer_keepalive_ok.sh \
		)

	killall ${list} ${list} &> /dev/null
}

main "$@"
