#!/bin/bash

. ${__ROOTFS__}/etc/jsock/jsock.in
. ${__ROOTFS__}/etc/upgrade/rsync.in

#
#$1:idx/buddy/ap
#
get_sysversion() {
	local idx="$1"

	case ${idx} in
	ap)
		${__ROOTFS__}/etc/jsock/jcmd.sh syn cat /etc/.version
		;;
	0 | 1 | 2)
		echo $(get_rootfs_version ${idx})
		;;
	buddy)
		echo $(get_rootfs_version $(rootfs_buddy))
		;;
	*)
		echo $(get_rootfs_version $(rootfs_current))
		;;
	esac
}

#
#$1:idx/buddy/ap
#
main() {
	local idx="$1"

	case ${idx} in
	all)
		get_sysversion 0
		get_sysversion 1
		get_sysversion 2
		get_sysversion ap
		;;
	*)
		get_sysversion ${idx}
		;;
	esac
}

main "$@"
