#!/bin/bash

. /etc/utils/utils.in

#userauth 1 $mac $group                        
#userauth 2 $mac $json                         
                                               
if [ $# -lt 3 ]; then                                
        echo "userauth version mac [string...]" >> /tmp/log/umdsh.log
        return 1;             
fi    

if [ $1 -eq 1 ]; then

mac="$2"
group="$3"                          
echo $group
filepath="/etc/um/group$group"

if [ -f "$filepath" ]; then 

onlineValue=`awk '/online/{print $2}'  $filepath`
flowMax=`awk '/flow/{print $2}'  $filepath`
rateMax=`awk '/intdownrate/{print $2}'  $filepath`
rateAvg=$rateMax
echo "onlineValue=$onlineValue, $flowMax, $rateAvg"

if [[ ! "$flowMax" =~ ^[0-9]+$ ]] ;then
	echo "flowMax=$flowMax value error!" >> /tmp/log/umdsh.log
	exit 1	
fi
if [[ ! "$onlineValue" =~ ^[0-9]+$ ]] ;then
	echo "onlineValue=$onlineValue value error!" >> /tmp/log/umdsh.log
	exit 1	
fi
if [[ ! "$rateAvg" =~ ^[0-9]+$ ]] ;then
	echo "rateAvg=$rageAvg error!" >> /tmp/log/umdsh.log
	exit 1	
fi
if [[ ! "$rateMax" =~ ^[0-9]+$ ]] ;then
	echo "rateMax=$rateMax error!" >> /tmp/log/umdsh.log
	exit 1	
fi

main() {
        local josn                                
                                                   
       #json=$(json_create wan/online/max $onlineValue wan/flow/up/max $flowMax wan/flow/down/max $flowMax wan/flow/all/max $flowMax wan/rate/up/max $rateMax wan/rate/up/avg $rateAvg wan/rate/down/max $rateMax wan/rate/down/avg $rateAvg wan/rate/all/max $rateMax wan/rate/all/avg $rateAvg) 
       json=$(json_create \
       wan/online/max $onlineValue \
       wan/flow/up/max $flowMax \
       wan/flow/down/max $flowMax \
       wan/flow/all/max $flowMax \
       wan/rate/up/max $rateMax \
       wan/rate/up/avg $rateAvg \
       wan/rate/down/max $rateMax \
       wan/rate/down/avg $rateAvg \
       wan/rate/all/max $rateMax \
       wan/rate/all/avg $rateAvg) 
        
        json=$(echo ${json} | jq -j -c .)                              
        echo "umc auth $mac $group $json"    
        umc auth $mac $group "$json"        
}                                          
                                           
main "$@"   
else
    echo "Error:couldn't find $filepath" >> /tmp/log/umdsh.log
fi
fi
